### ISSUE TITLE
.DS_Store is a useless file, should be removed

### ISSUE THREAD

**Issue by edjacob25** [sanchezpili6/vue-tech-showcase#4]
`.DS_Store` should be added to `.gitignore` and removed from the repo, it is a metadata file created by MacOS Finder

**Comment by sanchezpili6** [comment]
![image](https://user-images.githubusercontent.com/37568592/172450215-779d6be2-c998-414c-9aaa-48864e8dfb65.png)

**Comment by sanchezpili6** [comment]
I tried it like ".DS_Store", "/.DS_Store" and "**/.DS_Store" but it won't go away 😞
<img width="782" alt="Screen Shot 2022-06-07 at 10 55 10 AM" src="https://user-images.githubusercontent.com/37568592/172450292-e82c55c1-1bbd-498d-b41d-2a14a4470a8d.png">

**Comment by edjacob25** [comment]
You got to use `git rm` for that. And yes, also add it to `.gitgnore` .

So you can just do something like:
```sh
# First add them to .gitignore
echo "**/.DS_Store" >> .gitignore

# If the is only one file
git rm .DS_Store

# Or more
find -name ".DS_Store" -exec git rm {}

# Then 
git commit -m "Removed DS_store files"
```
